version: '2.32'

services:
  backfoodrecord:
    container_name: backfoodrecord
    image: backfoodrecord
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodRecord
      MYSQL_USER: sergio
      MYSQL_PASSWORD: hermanos16?
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql_volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql_volume:


